<?php load_partial("templates/header") ?>
<h1>Iniciar sesión</h1>
<?php load_partial("flash") ?>
<form action="<?= url("login", "signin") ?>" method="post">
<?= csrf_field_tag(); ?>
<div>
    <label for="email">Email</label>
    <input type="text" name="email" id="email" value="<?= get_value("email", "") ?>" required autofocus />
</div>
<div>
    <label for="password">Clave</label>
    <input type="password" name="password" id="password" required />
</div>
<div>
    <button type="submit" class="btn btn-primary">Entrar</button>
</div>
</form>
<?php load_partial("templates/footer") ?>
