<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">Pin</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li>
                <?= link_to("", "Home")?>
              </li>
              <li>
                <?= link_to("page/show", "Pages")?>
              </li>
              <li>
                <?= link_to("login/signin", "Login")?>
              </li>
              <li>
                <?= link_to("login/signout", "Logout")?>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
