<h1>Page#edit</h1>
<?= load_partial("flash") ?>
<?= form_tag("page/update", 'method="post"'); ?>
<div>
    <?= label_tag("titulo", "Título"); ?>
    <?= text_field_tag("titulo"); ?>
</div>
<div>
    <?= label_tag("cuerpo", "Cuerpo"); ?>
    <?= text_area_tag("cuerpo"); ?>
</div>
<div>
    <?= label_tag("credit_card", "Tarjeta"); ?>
    <?= select_tag("credit_card", options_for_select(["VISA", "MasterCard"]), "Seleccione"); ?>
</div>
<?= submit_tag("Enviar"); ?>
<?= link_to("page/show", "Cancelar"); ?>
<?= end_form_tag("page/update"); ?>