<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pin Default Template</title>
  <?= stylesheet_link('bootstrap'); ?>
  <style>
      body {
        padding-top: 60px; 
        /* 60px to make the container go all the way to the bottom of the topbar */
      }
  </style>
  <?= stylesheet_link('bootstrap-responsive'); ?>
  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
      <?= javascript_include_tag('html5shiv'); ?>
  <![endif]-->
</head>
<body>
  <?= load_partial('navbar'); ?>
  <div class="container"> 
    <?php echo $yield; ?>    
  </div><!-- end container -->
  <?= javascript_include_tag('jquery'); ?>
  <?= javascript_include_tag('bootstrap'); ?>
</body>
</html>
